# Posttest 4 KB
## Rivan Abdillah 
### 2009106025

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [34]:
ds = pd.read_csv("Cleaned_Laptop_Data.csv")
ds

brand     model processor_brand     processor_name processor_gnrtn  \
0     Lenovo   A6-9225             AMD  A6-9225 Processor            10th   
1     Lenovo   Ideapad             AMD           APU Dual            10th   
2      Avita      PURA             AMD           APU Dual            10th   
3      Avita      PURA             AMD           APU Dual            10th   
4      Avita      PURA             AMD           APU Dual            10th   
..       ...       ...             ...                ...             ...   
891     ASUS       ROG             AMD            Ryzen 9         Missing   
892     ASUS     Ryzen             AMD            Ryzen 9         Missing   
893     ASUS     Ryzen             AMD            Ryzen 9         Missing   
894  SAMSUNG    Galaxy        Qualcomm      Snapdragon 7c         Missing   
895   Lenovo  Thinkpad             AMD            Ryzen 5            10th   

      ram_gb ram_type      ssd      hdd       os  ... display_size  warranty  \
0    4 GB GB     DDR4     0 GB  1024 GB  Windows  ...      Missing         0   
1    4 GB GB     DDR4     0 GB   512 GB  Windows  ...      Missing         0   
2    4 GB GB     DDR4   128 GB     0 GB  Windows  ...      Missing         0   
3    4 GB GB     DDR4   128 GB     0 GB  Windows  ...      Missing         0   
4    4 GB GB     DDR4   256 GB     0 GB  Windows  ...      Missing         0   
..       ...      ...      ...      ...      ...  ...          ...       ...   
891  4 GB GB     DDR4  1024 GB     0 GB  Windows  ...           16         1   
892  4 GB GB     DDR4  1024 GB     0 GB  Windows  ...      Missing         1   
893  4 GB GB     DDR4  1024 GB     0 GB  Windows  ...           16         1   
894  4 GB GB  LPDDR4X     0 GB   512 GB  Windows  ...      Missing         0   
895  8 GB GB     DDR4   512 GB     0 GB      DOS  ...           14         0   

    Touchscreen msoffice  latest_price old_price discount  star_rating  \
0            No       No         24990     32790       23          3.7   
1            No       No         19590     21325        8          3.6   
2            No       No         19990     27990       28          3.7   
3            No       No         21490     27990       23          3.7   
4            No       No         24990     33490       25          3.7   
..          ...      ...           ...       ...      ...          ...   
891          No       No        144990    194990       25          0.0   
892          No       No        149990         0        0          0.0   
893          No       No        142990         0        0          0.0   
894          No       No         38990     47990       18          0.0   
895          No       No         57490     78400       26          4.2   

     ratings  reviews  
0         63       12  
1       1894      256  
2       1153      159  
3       1153      159  
4       1657      234  
..       ...      ...  
891        0        0  
892        0        0  
893        0        0  
894        0        0  
895       18        4  

[896 rows x 23 columns]

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   brand            896 non-null    object 
 1   model            896 non-null    object 
 2   processor_brand  896 non-null    object 
 3   processor_name   896 non-null    object 
 4   processor_gnrtn  896 non-null    object 
 5   ram_gb           896 non-null    object 
 6   ram_type         896 non-null    object 
 7   ssd              896 non-null    object 
 8   hdd              896 non-null    object 
 9   os               896 non-null    object 
 10  os_bit           896 non-null    object 
 11  graphic_card_gb  896 non-null    int64  
 12  weight           896 non-null    object 
 13  display_size     896 non-null    object 
 14  warranty         896 non-null    int64  
 15  Touchscreen      896 non-null    object 
 16  msoffice         896 non-null    object 
 17  latest_price    

### Cek jumlah record dan atribut pada dataset

In [5]:
ds.shape

(896, 23)

## Training set 70 : Test set 30

In [6]:
X = ds.iloc[:,:-1]
Y = ds.iloc[:,-1]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)

In [8]:
print("Jumlah x_train : ", x_train.shape)
print("Jumlah x_test : ", x_test.shape)
print("Jumlah y_train : ", y_train.shape)
print("Jumlah y_test : ", y_test.shape)

Jumlah x_train :  (627, 22)
Jumlah x_test :  (269, 22)
Jumlah y_train :  (627,)
Jumlah y_test :  (269,)


## Normalisasi data pada salah satu attribute menggunakan Min Max scaler

In [13]:
dsNum = ds["latest_price"]
dsNum

0       24990
1       19590
2       19990
3       21490
4       24990
        ...  
891    144990
892    149990
893    142990
894     38990
895     57490
Name: latest_price, Length: 896, dtype: int64

In [14]:
mm = MinMaxScaler()
X_scaled = mm.fit_transform(ds[['latest_price']])

In [18]:
hasil = pd.DataFrame(X_scaled)
hasil.head(10)

0
0  0.025701
1  0.013084
2  0.014019
3  0.017523
4  0.025701
5  0.025701
6  0.016145
7  0.018472
8  0.030161
9  0.042056

## Standarisasi pada dataset

In [19]:
ss = StandardScaler()
dataS = np.asarray(ds[["latest_price", "old_price", "ratings"]])
Scaled_data = ss.fit_transform(dataS)

In [23]:
print("Record data sebelum scaling : ")
print(dataS)
print("Nilai standar deviasi : ", np.std(dataS))
print("----------------------------------------------")
print("Record data setelah scaling : ")
print(Scaled_data)
print("Nilai standar deviasi : ", np.std(Scaled_data))

Record data sebelum scaling : 
[[ 24990  32790     63]
 [ 19590  21325   1894]
 [ 19990  27990   1153]
 ...
 [142990      0      0]
 [ 38990  47990      0]
 [ 57490  78400     18]]
Nilai standar deviasi :  57182.481459782146
----------------------------------------------
Record data setelah scaling : 
[[-1.10158395 -0.9938158  -0.27529528]
 [-1.21749528 -1.19969297  1.38068151]
 [-1.20890925 -1.08000947  0.71051286]
 ...
 [ 1.43129327 -1.58262631 -0.33227318]
 [-0.80107309 -0.72086917 -0.33227318]
 [-0.40396946 -0.17479635 -0.31599378]]
Nilai standar deviasi :  1.0


## Membuat Null

Dikarenakan dataset saya tidak memiliki nilai null

In [35]:
ds.iloc[:5,:10] = np.nan
ds

brand     model processor_brand processor_name processor_gnrtn  \
0        NaN       NaN             NaN            NaN             NaN   
1        NaN       NaN             NaN            NaN             NaN   
2        NaN       NaN             NaN            NaN             NaN   
3        NaN       NaN             NaN            NaN             NaN   
4        NaN       NaN             NaN            NaN             NaN   
..       ...       ...             ...            ...             ...   
891     ASUS       ROG             AMD        Ryzen 9         Missing   
892     ASUS     Ryzen             AMD        Ryzen 9         Missing   
893     ASUS     Ryzen             AMD        Ryzen 9         Missing   
894  SAMSUNG    Galaxy        Qualcomm  Snapdragon 7c         Missing   
895   Lenovo  Thinkpad             AMD        Ryzen 5            10th   

      ram_gb ram_type      ssd     hdd       os  ... display_size  warranty  \
0        NaN      NaN      NaN     NaN      NaN  ...      Missing         0   
1        NaN      NaN      NaN     NaN      NaN  ...      Missing         0   
2        NaN      NaN      NaN     NaN      NaN  ...      Missing         0   
3        NaN      NaN      NaN     NaN      NaN  ...      Missing         0   
4        NaN      NaN      NaN     NaN      NaN  ...      Missing         0   
..       ...      ...      ...     ...      ...  ...          ...       ...   
891  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...           16         1   
892  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...      Missing         1   
893  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...           16         1   
894  4 GB GB  LPDDR4X     0 GB  512 GB  Windows  ...      Missing         0   
895  8 GB GB     DDR4   512 GB    0 GB      DOS  ...           14         0   

    Touchscreen msoffice  latest_price old_price discount  star_rating  \
0            No       No         24990     32790       23          3.7   
1            No       No         19590     21325        8          3.6   
2            No       No         19990     27990       28          3.7   
3            No       No         21490     27990       23          3.7   
4            No       No         24990     33490       25          3.7   
..          ...      ...           ...       ...      ...          ...   
891          No       No        144990    194990       25          0.0   
892          No       No        149990         0        0          0.0   
893          No       No        142990         0        0          0.0   
894          No       No         38990     47990       18          0.0   
895          No       No         57490     78400       26          4.2   

     ratings  reviews  
0         63       12  
1       1894      256  
2       1153      159  
3       1153      159  
4       1657      234  
..       ...      ...  
891        0        0  
892        0        0  
893        0        0  
894        0        0  
895       18        4  

[896 rows x 23 columns]

## Data Cleaning nilai null

In [36]:
ds.isna().sum()

brand              5
model              5
processor_brand    5
processor_name     5
processor_gnrtn    5
ram_gb             5
ram_type           5
ssd                5
hdd                5
os                 5
os_bit             0
graphic_card_gb    0
weight             0
display_size       0
warranty           0
Touchscreen        0
msoffice           0
latest_price       0
old_price          0
discount           0
star_rating        0
ratings            0
reviews            0
dtype: int64

### Mengubah nilai null bertipe data bilangan bulat

In [37]:
imp = SimpleImputer(strategy = 'most_frequent')
ds["processor_brand"] = imp.fit_transform(ds[["processor_brand"]])
ds["ram_gb"] = imp.fit_transform(ds[["ram_gb"]])
ds["discount"] = imp.fit_transform(ds[["discount"]])
ds["Touchscreen"] = imp.fit_transform(ds[["Touchscreen"]])
ds["weight"] = imp.fit_transform(ds[["weight"]])
ds["msoffice"] = imp.fit_transform(ds[["msoffice"]])
ds["reviews"] = imp.fit_transform(ds[["reviews"]])
print("Jumlah Null: ")
ds.isna().sum()

Jumlah Null: 


brand              5
model              5
processor_brand    0
processor_name     5
processor_gnrtn    5
ram_gb             0
ram_type           5
ssd                5
hdd                5
os                 5
os_bit             0
graphic_card_gb    0
weight             0
display_size       0
warranty           0
Touchscreen        0
msoffice           0
latest_price       0
old_price          0
discount           0
star_rating        0
ratings            0
reviews            0
dtype: int64

### Mengubah nilai null bertipe angka bilangan desimal

In [40]:
imp = SimpleImputer(strategy = 'mean')
ds["warranty"] = imp.fit_transform(ds[["warranty"]])
ds["star_rating"] = imp.fit_transform(ds[["star_rating"]])
print("Jumlah Null: ")
ds.isna().sum()

Jumlah Null: 


brand              5
model              5
processor_brand    0
processor_name     5
processor_gnrtn    5
ram_gb             0
ram_type           5
ssd                5
hdd                5
os                 5
os_bit             0
graphic_card_gb    0
weight             0
display_size       0
warranty           0
Touchscreen        0
msoffice           0
latest_price       0
old_price          0
discount           0
star_rating        0
ratings            0
reviews            0
dtype: int64

### Mengubah nilai null bertipe data kategorikal

In [46]:
imp = SimpleImputer(strategy = 'most_frequent')
ds["processor_gnrtn"] = imp.fit_transform(ds[["processor_gnrtn"]])
ds["os"] = imp.fit_transform(ds[["os"]])
ds["brand"] = imp.fit_transform(ds[["brand"]])
ds["model"] = imp.fit_transform(ds[["model"]])
ds["processor_name"] = imp.fit_transform(ds[["processor_name"]])
ds["ssd"] = imp.fit_transform(ds[["ssd"]])
ds["hdd"] = imp.fit_transform(ds[["hdd"]])
print("Jumlah Null: ")
ds.isna().sum()

Jumlah Null: 


brand                0
model                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
display_size         0
warranty             0
Touchscreen          0
msoffice             0
latest_price         0
old_price            0
discount             0
star_rating          0
ratings              0
reviews              0
[processor_gnrtn]    0
dtype: int64

## Data Cleaning Duplikat

In [47]:
ds[ds.duplicated()]

brand     model processor_brand processor_name processor_gnrtn  \
24      ASUS   EeeBook           Intel   Celeron Dual         Missing   
59      ASUS  VivoBook           Intel        Core i3            11th   
66   Infinix    INBook           Intel        Core i3            10th   
142     ASUS  VivoBook           Intel        Core i3            10th   
238       LG      Gram           Intel        Core i5            11th   
298     ASUS  VivoBook           Intel        Core i5            11th   
413     ASUS   ZenBook           Intel        Core i5            11th   
430    Avita     Liber           Intel        Core i5             7th   
433    Avita     Liber           Intel        Core i5             7th   
439    Avita     Liber           Intel        Core i5             8th   
520    Avita     Liber           Intel        Core i7             8th   
521    Avita     Liber           Intel        Core i7             8th   
522    Avita     Liber           Intel        Core i7             8th   
523    Avita     Liber           Intel        Core i7             8th   
524    Avita     Liber           Intel        Core i7             8th   
658    APPLE   MacBook              M1             M1            10th   
660    APPLE   MacBook              M1             M1            10th   
661    APPLE   MacBook              M1             M1            10th   
672    APPLE   MacBook              M1             M1            10th   
678    APPLE   MacBook              M1             M1            10th   

       ram_gb ram_type      ssd     hdd       os  ... warranty  Touchscreen  \
24    4 GB GB     DDR4     0 GB  512 GB  Windows  ...      0.0           No   
59    8 GB GB     DDR4   256 GB    0 GB  Windows  ...      1.0           No   
66    8 GB GB  LPDDR4X   256 GB    0 GB  Windows  ...      0.0           No   
142   4 GB GB     DDR4   512 GB    0 GB  Windows  ...      1.0           No   
238   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
298  16 GB GB     DDR4   512 GB    0 GB  Windows  ...      1.0           No   
413   8 GB GB  LPDDR4X   512 GB    0 GB  Windows  ...      1.0          Yes   
430   8 GB GB     DDR4   512 GB    0 GB  Windows  ...      0.0           No   
433   8 GB GB     DDR4   512 GB    0 GB  Windows  ...      0.0           No   
439   8 GB GB     DDR4   512 GB    0 GB  Windows  ...      0.0           No   
520   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
521   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
522   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
523   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
524   8 GB GB     DDR4   256 GB    0 GB  Windows  ...      0.0           No   
658   8 GB GB     DDR4   256 GB    0 GB      Mac  ...      1.0           No   
660  16 GB GB     DDR4   256 GB    0 GB      Mac  ...      1.0           No   
661   8 GB GB     DDR4   256 GB    0 GB      Mac  ...      1.0           No   
672   8 GB GB     DDR4   512 GB    0 GB      Mac  ...      1.0           No   
678  16 GB GB     DDR4  1024 GB    0 GB      Mac  ...      1.0           No   

    msoffice latest_price  old_price discount star_rating  ratings  reviews  \
24        No        22990      27990       17         0.0        0        0   
59        No        45990      58990       22         4.5      816      147   
66        No        32990      49999       34         4.3     1221      265   
142       No        40990      49990       18         4.4     4008      519   
238       No        76990     106000       27         0.0        0        0   
298       No        59990      80990       25         0.0        0        0   
413       No        99990     122990       18         0.0        0        0   
430       No        65556      79990       18         0.0        0        0   
433       No        65556      79990       18         0.0        0        0   
439       No        730

In [48]:
ds.drop_duplicates(inplace=True)

In [50]:
print("Nilai Duplikat:",ds.duplicated().sum())

Nilai Duplikat: 0


## Mengubah tipe data angka

In [54]:
encoder = OrdinalEncoder()
ds["old_priceENC"] = encoder.fit_transform(ds[["brand"]])
ds.head()

brand    model processor_brand processor_name processor_gnrtn   ram_gb  \
0  ASUS  Missing           Intel        Core i5            11th  8 GB GB   
1  ASUS  Missing           Intel        Core i5            11th  8 GB GB   
2  ASUS  Missing           Intel        Core i5            11th  8 GB GB   
3  ASUS  Missing           Intel        Core i5            11th  8 GB GB   
4  ASUS  Missing           Intel        Core i5            11th  8 GB GB   

  ram_type     ssd   hdd       os  ... Touchscreen  msoffice latest_price  \
0     DDR4  512 GB  0 GB  Windows  ...          No        No        24990   
1     DDR4  512 GB  0 GB  Windows  ...          No        No        19590   
2     DDR4  512 GB  0 GB  Windows  ...          No        No        19990   
3     DDR4  512 GB  0 GB  Windows  ...          No        No        21490   
4     DDR4  512 GB  0 GB  Windows  ...          No        No        24990   

  old_price  discount star_rating ratings  reviews  [processor_gnrtn]  \
0     32790        23         3.7      63       12               11th   
1     21325         8         3.6    1894      256               11th   
2     27990        28         3.7    1153      159               11th   
3     27990        23         3.7    1153      159               11th   
4     33490        25         3.7    1657      234               11th   

   old_priceENC  
0           2.0  
1           2.0  
2           2.0  
3           2.0  
4           2.0  

[5 rows x 25 columns]

In [55]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 876 entries, 0 to 895
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   brand              876 non-null    object 
 1   model              876 non-null    object 
 2   processor_brand    876 non-null    object 
 3   processor_name     876 non-null    object 
 4   processor_gnrtn    876 non-null    object 
 5   ram_gb             876 non-null    object 
 6   ram_type           876 non-null    object 
 7   ssd                876 non-null    object 
 8   hdd                876 non-null    object 
 9   os                 876 non-null    object 
 10  os_bit             876 non-null    object 
 11  graphic_card_gb    876 non-null    int64  
 12  weight             876 non-null    object 
 13  display_size       876 non-null    object 
 14  warranty           876 non-null    float64
 15  Touchscreen        876 non-null    object 
 16  msoffice           876 non

## One Hot Encoding

In [57]:
encoderHot = OneHotEncoder(sparse=False) 
old_priceEnc = encoderHot.fit_transform(ds[["old_price"]]) 
old_priceEnc = pd.DataFrame(old_priceEnc) 
ds = ds.join(old_priceEnc) 
ds 

brand     model processor_brand processor_name processor_gnrtn  \
0       ASUS   Missing           Intel        Core i5            11th   
1       ASUS   Missing           Intel        Core i5            11th   
2       ASUS   Missing           Intel        Core i5            11th   
3       ASUS   Missing           Intel        Core i5            11th   
4       ASUS   Missing           Intel        Core i5            11th   
..       ...       ...             ...            ...             ...   
891     ASUS       ROG             AMD        Ryzen 9         Missing   
892     ASUS     Ryzen             AMD        Ryzen 9         Missing   
893     ASUS     Ryzen             AMD        Ryzen 9         Missing   
894  SAMSUNG    Galaxy        Qualcomm  Snapdragon 7c         Missing   
895   Lenovo  Thinkpad             AMD        Ryzen 5            10th   

      ram_gb ram_type      ssd     hdd       os  ...  554  555  556  557  558  \
0    8 GB GB     DDR4   512 GB    0 GB  Windows  ...  0.0  0.0  0.0  0.0  0.0   
1    8 GB GB     DDR4   512 GB    0 GB  Windows  ...  0.0  0.0  0.0  0.0  0.0   
2    8 GB GB     DDR4   512 GB    0 GB  Windows  ...  0.0  0.0  0.0  0.0  0.0   
3    8 GB GB     DDR4   512 GB    0 GB  Windows  ...  0.0  0.0  0.0  0.0  0.0   
4    8 GB GB     DDR4   512 GB    0 GB  Windows  ...  0.0  0.0  0.0  0.0  0.0   
..       ...      ...      ...     ...      ...  ...  ...  ...  ...  ...  ...   
891  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...  NaN  NaN  NaN  NaN  NaN   
892  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...  NaN  NaN  NaN  NaN  NaN   
893  4 GB GB     DDR4  1024 GB    0 GB  Windows  ...  NaN  NaN  NaN  NaN  NaN   
894  4 GB GB  LPDDR4X     0 GB  512 GB  Windows  ...  NaN  NaN  NaN  NaN  NaN   
895  8 GB GB     DDR4   512 GB    0 GB      DOS  ...  NaN  NaN  NaN  NaN  NaN   

     559  560  561  562  563  
0    0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  
891  NaN  NaN  NaN  NaN  NaN  
892  NaN  NaN  NaN  NaN  NaN  
893  NaN  NaN  NaN  NaN  NaN  
894  NaN  NaN  NaN  NaN  NaN  
895  NaN  NaN  NaN  NaN  NaN  

[876 rows x 589 columns]