# POSTTEST 7 KB
## Rivan Abdillah (2009106025)

In [1]:
import tensorflow as tf
import numpy as np

### Tensor dengan shape(5,5) dengan nilai random

In [15]:
random_tensor = tf.Variable(tf.random.normal([5,5],mean=10))

In [16]:
random_tensor

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 9.054784, 10.383181,  8.829741,  9.5535  ,  8.393227],
       [10.630184,  8.308507, 10.725995,  9.54934 , 11.242583],
       [ 9.139395,  8.789129, 10.615953,  9.326111,  8.779099],
       [ 9.148739,  9.354665,  9.027039, 11.524569, 10.761619],
       [ 9.656995,  9.09507 ,  8.468249,  8.957924, 12.712107]],
      dtype=float32)>

### Tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima

In [10]:
list = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,101]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)
prime_tensor = tf.reshape(prime_tensor,[5,5])

In [11]:
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  67.,  71.],
       [ 73.,  79.,  83.,  89., 101.]], dtype=float32)>

### Tampilan dimensi dari kedua variable

In [17]:
print(random_tensor.get_shape())

(5, 5)


In [18]:
print(prime_tensor.get_shape())

(5, 5)


### Perhitungan aritmetika 2 variable antara random dan prime tensor

In [19]:
a = random_tensor
b = prime_tensor

In [21]:
# penjumlahan tensor
print(tf.add(a,b))

tf.Tensor(
[[ 11.054784  13.383181  13.829741  16.553501  19.393227]
 [ 23.630184  25.308506  29.725994  32.54934   40.242584]
 [ 40.139397  45.78913   51.61595   52.32611   55.7791  ]
 [ 62.14874   68.35467   70.02704   78.52457   81.76162 ]
 [ 82.657     88.09507   91.46825   97.957924 113.712105]], shape=(5, 5), dtype=float32)


In [26]:
# pengurangan tensor
print(tf.math.subtract(a,b))

tf.Tensor(
[[  7.054784    7.3831806   3.8297405   2.5535002  -2.6067734]
 [ -2.3698158  -8.691493   -8.274005  -13.45066   -17.757416 ]
 [-21.860605  -28.21087   -30.384047  -33.67389   -38.2209   ]
 [-43.85126   -49.645336  -51.97296   -55.475433  -60.23838  ]
 [-63.343006  -69.90493   -74.53175   -80.042076  -88.287895 ]], shape=(5, 5), dtype=float32)


In [27]:
# perkalian tensor
print(tf.multiply(a,b))

tf.Tensor(
[[  18.109568   31.149542   44.148705   66.874504   92.32549 ]
 [ 138.1924    141.24461   203.7939    219.63483   326.0349  ]
 [ 283.32123   325.19778   435.2541    401.02277   412.61768 ]
 [ 484.88315   551.92523   550.64935   772.1461    764.07495 ]
 [ 704.96063   718.5105    702.8647    797.25525  1283.9227  ]], shape=(5, 5), dtype=float32)


In [28]:
# pembagian tensor
print(tf.divide(a,b))

tf.Tensor(
[[4.527392   3.4610603  1.765948   1.3647858  0.7630206 ]
 [0.81770647 0.4887357  0.5645261  0.4151887  0.3876753 ]
 [0.29481918 0.23754403 0.2589257  0.2168863  0.18678935]
 [0.17261772 0.15855365 0.14798424 0.17200848 0.1515721 ]
 [0.1322876  0.11512747 0.1020271  0.10065083 0.12586245]], shape=(5, 5), dtype=float32)


In [29]:
print(tf.matmul(a,b))

tf.Tensor(
[[1545.8539 1757.1003 1883.975  2068.957  2341.727 ]
 [1788.6005 2021.5721 2166.4226 2367.1204 2675.5046]
 [1596.7902 1813.4131 1945.5026 2128.801  2403.2107]
 [1816.1466 2050.5935 2189.804  2397.2913 2701.36  ]
 [1802.8193 2029.6864 2169.8276 2372.4788 2687.927 ]], shape=(5, 5), dtype=float32)


### Nilai maksimal dan minimal dari variable random_tensor

In [30]:
print("Nilai Maksimal : ",tf.argmax(random_tensor))
print("Nilai Minimal : ",tf.argmin(random_tensor))

Nilai Maksimal :  tf.Tensor([1 0 1 3 4], shape=(5,), dtype=int64)
Nilai Minimal :  tf.Tensor([0 1 4 4 0], shape=(5,), dtype=int64)


### Penggabungan variable random_tensor dengan prime_tensor

In [33]:
print(tf.concat([random_tensor, prime_tensor], axis=0))

tf.Tensor(
[[  9.054784  10.383181   8.829741   9.5535     8.393227]
 [ 10.630184   8.308507  10.725995   9.54934   11.242583]
 [  9.139395   8.789129  10.615953   9.326111   8.779099]
 [  9.148739   9.354665   9.027039  11.524569  10.761619]
 [  9.656995   9.09507    8.468249   8.957924  12.712107]
 [  2.         3.         5.         7.        11.      ]
 [ 13.        17.        19.        23.        29.      ]
 [ 31.        37.        41.        43.        47.      ]
 [ 53.        59.        61.        67.        71.      ]
 [ 73.        79.        83.        89.       101.      ]], shape=(10, 5), dtype=float32)


### Tampilkan hasil sorting dari kedua variable di atas

In [34]:
# random_tensor descending
print("Sebelum sorting :", random_tensor)
rsort = tf.sort(random_tensor, direction="DESCENDING")
print("Setelah descending :", rsort)

Sebelum sorting : <tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[ 9.054784, 10.383181,  8.829741,  9.5535  ,  8.393227],
       [10.630184,  8.308507, 10.725995,  9.54934 , 11.242583],
       [ 9.139395,  8.789129, 10.615953,  9.326111,  8.779099],
       [ 9.148739,  9.354665,  9.027039, 11.524569, 10.761619],
       [ 9.656995,  9.09507 ,  8.468249,  8.957924, 12.712107]],
      dtype=float32)>
Setelah descending : tf.Tensor(
[[10.383181  9.5535    9.054784  8.829741  8.393227]
 [11.242583 10.725995 10.630184  9.54934   8.308507]
 [10.615953  9.326111  9.139395  8.789129  8.779099]
 [11.524569 10.761619  9.354665  9.148739  9.027039]
 [12.712107  9.656995  9.09507   8.957924  8.468249]], shape=(5, 5), dtype=float32)


In [36]:
# prime_Tensor descending
print("Sebelum sorting :", prime_tensor)
psort = tf.sort(prime_tensor, direction="DESCENDING")
print("Setelah descending :", psort)

Sebelum sorting : tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  67.  71.]
 [ 73.  79.  83.  89. 101.]], shape=(5, 5), dtype=float32)
Setelah descending : tf.Tensor(
[[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 71.  67.  61.  59.  53.]
 [101.  89.  83.  79.  73.]], shape=(5, 5), dtype=float32)
